/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.galileo.netbeans.module;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.TrayIcon.MessageType;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;
import javax.swing.event.UndoableEditEvent;
import javax.swing.undo.StateEdit;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.LifecycleManager;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.UndoRedo;
import org.openide.util.AsyncGUIJob;
import org.openide.util.Exceptions;
import org.openide.util.ImageUtilities;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//com.galileo.netbeans.module//My//EN",
autostore = false)
@TopComponent.Description(preferredID = "MyTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.galileo.netbeans.module.MyTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MyAction",
preferredID = "MyTopComponent")
public final class MyTopComponent extends TopComponent implements UndoRedo.Provider {

   private DefaultComboBoxModel model1 = new DefaultComboBoxModel();
   private DefaultComboBoxModel model2 = new DefaultComboBoxModel();
   private DefaultComboBoxModel model3 = new DefaultComboBoxModel();
   
   private UndoRedo.Manager manager = new UndoRedo.Manager();
   
   private MyObject obj = new MyObject();
   
   public MyTopComponent() {
      initComponents();
      setName(NbBundle.getMessage(MyTopComponent.class, "CTL_MyTopComponent"));
      setToolTipText(NbBundle.getMessage(MyTopComponent.class, "HINT_MyTopComponent"));

      Utilities.attachInitJob(items1, new AsyncGUIJob(){
         @Override
         public void construct() {
            try     {
               Thread.sleep(5000);
            } catch (InterruptedException ex) {
               Exceptions.printStackTrace(ex);
            }

            for(int i = 0; i < 20; i++) {
               model1.addElement("Item " + i);
            }
         }
         
         @Override
         public void finished() {
            items1.setModel(model1);
         }
      });
      
      SwingWorker<DefaultComboBoxModel, String> worker1 = new SwingWorker<DefaultComboBoxModel, String>() {
         
         @Override
         protected DefaultComboBoxModel doInBackground() throws Exception {
            for(int i = 0; i < 20; i++) {
               model2.addElement("Item " + i);
            }
            return model2;
         }

         @Override
         protected void done() {
            try {
               items2.setModel(get());
            } catch (Exception ignore) {}
         }
      };

      worker1.execute();
      
      
      items3.setModel(model3);
      
      SwingWorker<DefaultComboBoxModel, String> worker2 = new SwingWorker<DefaultComboBoxModel, String>() {
         
         @Override
         protected DefaultComboBoxModel doInBackground() throws Exception {
            for(int i = 0; i < 20; i++) {
               Thread.sleep(500);
               publish("Item " + i);
            }
            return model3;
         }
         
         @Override
         protected void process(List<String> chunks) {
            model3.addElement(chunks.iterator().next());
         }
         
      };

      worker2.execute();

      // Undo / Redo support for Document data models
      text1.getDocument().addUndoableEditListener(manager);
   }
   
   @Override
   public UndoRedo getUndoRedo() {
      return manager;
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      items2 = new JComboBox(new String[]{"Loading..."});
      items1 = new JComboBox(new String[]{"Loading..."});
      items3 = new javax.swing.JComboBox();
      jLabel4 = new javax.swing.JLabel();
      jPanel5 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      uri = new javax.swing.JTextField();
      browse = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();
      file = new javax.swing.JTextField();
      open = new javax.swing.JButton();
      edit = new javax.swing.JButton();
      print = new javax.swing.JButton();
      search = new javax.swing.JButton();
      jLabel7 = new javax.swing.JLabel();
      email = new javax.swing.JTextField();
      mail = new javax.swing.JButton();
      openMail = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      changeState = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      shutdown = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      prop = new javax.swing.JTextField();
      save = new javax.swing.JButton();
      load = new javax.swing.JButton();
      text1 = new javax.swing.JTextField();

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jPanel1.border.title"))); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel1.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel2.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel4.text")); // NOI18N

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(jLabel2)
               .addComponent(jLabel4))
            .addGap(8, 8, 8)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(items2, 0, 82, Short.MAX_VALUE)
               .addComponent(items1, 0, 82, Short.MAX_VALUE)
               .addComponent(items3, 0, 82, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(items1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(items2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(items3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addContainerGap())
      );

      jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jPanel5.border.title"))); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel5.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(browse, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.browse.text")); // NOI18N
      browse.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            browseActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel6.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(open, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.open.text")); // NOI18N
      open.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            openActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(edit, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.edit.text")); // NOI18N
      edit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            editActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(print, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.print.text")); // NOI18N
      print.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            printActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(search, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.search.text")); // NOI18N
      search.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel7.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(mail, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.mail.text")); // NOI18N
      mail.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mailActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(openMail, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.openMail.text")); // NOI18N
      openMail.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            openMailActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(browse, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(uri, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel6)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(search))
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(open)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(edit)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(print))
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel7)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                  .addComponent(openMail, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(mail)))
            .addContainerGap())
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(uri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(browse)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(search))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(open)
               .addComponent(edit)
               .addComponent(print))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(mail)
               .addComponent(openMail))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jPanel4.border.title"))); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(changeState, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.changeState.text")); // NOI18N
      changeState.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            changeStateActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jButton1.text")); // NOI18N
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
               .addComponent(changeState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(changeState)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addContainerGap(14, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jPanel3.border.title"))); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(shutdown, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.shutdown.text")); // NOI18N
      shutdown.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            shutdownActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(shutdown, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(shutdown)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jPanel2.border.title"))); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.jLabel3.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(save, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.save.text")); // NOI18N
      save.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(load, org.openide.util.NbBundle.getMessage(MyTopComponent.class, "MyTopComponent.load.text")); // NOI18N
      load.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            loadActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(prop, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(load, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(save)
               .addComponent(load))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 406, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(15, 15, 15)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 318, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

   private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().browse(new URI(uri.getText()));
         } catch(Exception ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_browseActionPerformed

   private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().open(new File(file.getText()));
         } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_openActionPerformed

   private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().edit(new File(file.getText()));
         } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_editActionPerformed

   private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().print(new File(file.getText()));
         } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_printActionPerformed

   private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      JFileChooser chooser = new JFileChooser();
      int ret = chooser.showOpenDialog(null);
      
      if(ret == JFileChooser.APPROVE_OPTION) {
         file.setText(chooser.getSelectedFile().getAbsolutePath());
      }
}//GEN-LAST:event_searchActionPerformed

   private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().mail(new URI("mailto:" + email.getText()));
         } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_mailActionPerformed

   private void openMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMailActionPerformed
      if(Desktop.isDesktopSupported()) {
         try {
            Desktop.getDesktop().mail();
         } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
         }
      }
}//GEN-LAST:event_openMailActionPerformed

   private void changeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStateActionPerformed
      if(SystemTray.isSupported()) {
         SystemTray tray = SystemTray.getSystemTray();
         TrayIcon icons[] = tray.getTrayIcons();
         if(icons.length > 0) {
            Image img = ImageUtilities.loadImage("com/galileo/netbeans/module/icon2.gif");
            icons[0].setImage(img);
         }
      }
}//GEN-LAST:event_changeStateActionPerformed

   private void shutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownActionPerformed
      LifecycleManager.getDefault().exit();
}//GEN-LAST:event_shutdownActionPerformed

   private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      StateEdit se = new StateEdit(obj);
      manager.undoableEditHappened(new UndoableEditEvent(obj, se));
      obj.setProp(prop.getText());
      se.end();
}//GEN-LAST:event_saveActionPerformed

   private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
      prop.setText(obj.getProp());
}//GEN-LAST:event_loadActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Installer.displayTrayMessage("Caption", "Das ist meine erste System Tray Message", MessageType.INFO);
   }//GEN-LAST:event_jButton1ActionPerformed

      // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton browse;
   private javax.swing.JButton changeState;
   private javax.swing.JButton edit;
   private javax.swing.JTextField email;
   private javax.swing.JTextField file;
   private javax.swing.JComboBox items1;
   private javax.swing.JComboBox items2;
   private javax.swing.JComboBox items3;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JButton load;
   private javax.swing.JButton mail;
   private javax.swing.JButton open;
   private javax.swing.JButton openMail;
   private javax.swing.JButton print;
   private javax.swing.JTextField prop;
   private javax.swing.JButton save;
   private javax.swing.JButton search;
   private javax.swing.JButton shutdown;
   private javax.swing.JTextField text1;
   private javax.swing.JTextField uri;
   // End of variables declaration//GEN-END:variables
   @Override
   public void componentOpened() {
      // TODO add custom code on component opening
   }

   @Override
   public void componentClosed() {
      // TODO add custom code on component closing
   }

   void writeProperties(java.util.Properties p) {
      // better to version settings since initial version as advocated at
      // http://wiki.apidesign.org/wiki/PropertyFiles
      p.setProperty("version", "1.0");
      // TODO store your settings
   }

   void readProperties(java.util.Properties p) {
      String version = p.getProperty("version");
      // TODO read your settings according to their version
   }
}
