/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.galileo.netbeans.module;

import java.io.File;
import java.util.Collection;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.NbBundle;
import org.openide.util.NbCollections;

public final class PlaylistVisualPanel2 extends JPanel {

   public static final String PROP_TRACKS = "tracks";

   private DefaultListModel model = new DefaultListModel();

   public PlaylistVisualPanel2() {
      initComponents();
      tracks.setModel(model);
   }

   @Override
   public String getName() {
      return NbBundle.getBundle(PlaylistWizardPanel2.class).getString("Panel2.Name");
   }

   public Collection<File> getTracks() {
      return Collections.list(NbCollections.checkedEnumerationByFilter(model.elements(), File.class, false));
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      addTrack = new javax.swing.JButton();
      removeTrack = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tracks = new javax.swing.JList();

      org.openide.awt.Mnemonics.setLocalizedText(addTrack, org.openide.util.NbBundle.getMessage(PlaylistVisualPanel2.class, "PlaylistVisualPanel2.addTrack.text")); // NOI18N
      addTrack.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addTrackActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(removeTrack, org.openide.util.NbBundle.getMessage(PlaylistVisualPanel2.class, "PlaylistVisualPanel2.removeTrack.text")); // NOI18N
      removeTrack.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeTrackActionPerformed(evt);
         }
      });

      jScrollPane1.setViewportView(tracks);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(removeTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(addTrack))
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(addTrack)
               .addComponent(removeTrack))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

   private void addTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrackActionPerformed
      JFileChooser chooser = new JFileChooser();
      chooser.setFileFilter(new FileNameExtensionFilter("MP3 Musikdateien", "mp3"));
      chooser.setMultiSelectionEnabled(true);
      
      if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
         for(File f : chooser.getSelectedFiles()) {
            model.addElement(f);
         }
      }
}//GEN-LAST:event_addTrackActionPerformed

   private void removeTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTrackActionPerformed
      int index = tracks.getSelectedIndex();
      if(index != -1) {
         model.remove(index);
      }
}//GEN-LAST:event_removeTrackActionPerformed
      // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addTrack;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton removeTrack;
   private javax.swing.JList tracks;
   // End of variables declaration//GEN-END:variables
}
