/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.galileo.netbeans.module;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbPreferences;

final class ModuleOptions1Panel extends javax.swing.JPanel  implements DocumentListener {

   private final ModuleOptions1PanelController controller;

   ModuleOptions1Panel(ModuleOptions1PanelController controller) {
      this.controller = controller;
      initComponents();
      option1.getDocument().addDocumentListener(this);
   }

   
   @Override
   public void insertUpdate(DocumentEvent arg0) {
      controller.changed();
   }
   
   @Override
   public void removeUpdate(DocumentEvent arg0) {
      controller.changed();
   }
   
   @Override
   public void changedUpdate(DocumentEvent arg0) {
      controller.changed();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      option2 = new javax.swing.JTextField();
      option1 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();

      option2.setText(org.openide.util.NbBundle.getMessage(ModuleOptions1Panel.class, "ModuleOptions1Panel.option2.text")); // NOI18N

      option1.setText(org.openide.util.NbBundle.getMessage(ModuleOptions1Panel.class, "ModuleOptions1Panel.option1.text")); // NOI18N
      option1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            option1ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ModuleOptions1Panel.class, "ModuleOptions1Panel.jLabel1.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ModuleOptions1Panel.class, "ModuleOptions1Panel.jLabel2.text")); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 435, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(option2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(option1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 74, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(option1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(12, 12, 12)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(option2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
      // TODO add your handling code here:
}//GEN-LAST:event_option1ActionPerformed

   void load() {
      option1.setText(NbPreferences.forModule(ModuleOptions1Panel.class).get("option1", "default"));
   }

   void store() {
      NbPreferences.forModule(ModuleOptions1Panel.class).put("option1", option1.getText());
   }

   boolean valid() {
      System.out.println("isValid");
      if(option1.getText().length() == 0) {
         return false;
      } else {
         return true;
      }
   }
      // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JTextField option1;
   private javax.swing.JTextField option2;
   // End of variables declaration//GEN-END:variables
}
